In [5]:
import pandas as pd
import matplotlib as mp

In [6]:
import urllib.request
import wget

In [7]:
url = 'https://data.cityofchicago.org/resource/38sz-xyf4.json'
wget.download(url, '/Users/Aren Kabarajian/Documents/NYU CUSP/Urban Spatial Final')

'/Users/Aren Kabarajian/Documents/NYU CUSP/Urban Spatial Final/38sz-xyf4 (1).json'

In [8]:
df = pd.read_json(url)

In [9]:
df

,event,start_time,address,description,web_page,event_type,audience,recurring_event,latitude,longitude,location,:@computed_region_rpca_8um6,:@computed_region_vrxf_vc4k,:@computed_region_6mkv_f3dw,:@computed_region_bdys_3d7i,:@computed_region_43wa_7qmu,end_time,address_details
0,Ride of Silence,2021-05-19 18:00:00,50 W. Washington,"On Wednesday, May 15th, Chicago cyclists will ...",{'url': 'http://rideofsilencechicago.weebly.co...,Bike Ride,Adult | Children | LGBTQ | Seniors | Teens,Yes,41.883322,-87.629775,"{'latitude': '41.88332219914999', 'longitude':...",41.0,38.0,14310.0,92.0,36.0,NaT,NaN
1,Bike the Drive and Post Ride Festival,2020-05-24 07:00:00,Lake Shore Drive,Lake Shore Drive is closed to cars and open to...,{'url': 'http://bikethedrive.org/about'},Festival | Bike Ride,All,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-24 12:00:00,NaN
2,Ride of Silence,2020-05-20 18:00:00,50 W. Washington,"On Wednesday, May 15th, Chicago cyclists will ...",{'url': 'http://rideofsilencechicago.weebly.co...,Bike Ride,Adult | Children | LGBTQ | Seniors | Teens,Yes,41.883322,-87.629775,"{'latitude': '41.88332219914999', 'longitude':...",41.0,38.0,14310.0,92.0,36.0,NaT,NaN
3,Chicago Moves Day,2020-05-06 11:30:00,"377 East Randolph St., Chicago, IL 60601",Chicago Moves Day is a citywide initiative to ...,NaN,NaN,Adult | Children | LGBTQ | Seniors | Teens,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-05-06 13:30:00,Maggie Daley Park
4,The Black Women's Expo,2020-04-05 10:00:00,2301 South King Drive,The Black Womenâ€™s Expo is an event offering op...,{'url': 'https://10times.com/black-womens-expo'},NaN,Expo,Yes,41.851200,-87.618819,"{'latitude': '41.85119983657814', 'longitude':...",40.0,34.0,21194.0,193.0,10.0,2020-04-05 19:00:00,McCormick
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,"LGBT Chamber of Commerce ""Celebration of Black...",2018-02-22 18:00:00,305 E Garfield Blvd,Panel discussion of Black LGBT businesses,NaN,Panel Discussion,LGBTQ,No,41.794317,-87.618979,"{'latitude': '41.7943165619035', 'longitude': ...",60.0,7.0,22260.0,402.0,9.0,2018-02-22 21:00:00,Currency Exchange Cafe
490,Lawndale Cinema - Black Panther Screening and ...,2018-02-15 16:00:00,3330 W. Roosevelt Rd.,Health Fair during reception period prior to a...,NaN,Health Fair,Adult | Children | LGBTQ | Seniors,No,41.866474,-87.709387,"{'latitude': '41.86647384666724', 'longitude':...",30.0,30.0,21572.0,98.0,14.0,2018-02-15 20:00:00,NaN
491,Quiet Storm: The Art & Times of Black LGBTQ Life,2018-02-01 18:00:00,3656 N. Halsted,Overview of Black LGBTQ Art and Lifestyle,NaN,LGBTQ,Adult | LGBTQ,No,41.948966,-87.649683,"{'latitude': '41.94896619671428', 'longitude':...",53.0,57.0,21186.0,727.0,25.0,2018-02-01 21:00:00,NaN
492,Community Resilience Workshop,2017-04-26 16:00:00,6220 S. Stony Island,"Through shared experiences, we will explore id...",{'url': 'https://www.chicagohan.org/ViewsFlash...,Workshop,Adult | In/Out of School service providers; Co...,No,41.782235,-87.586651,"{'latitude': '41.78223538790277', 'longitude':...",60.0,9.0,22260.0,469.0,33.0,2017-04-26 18:00:00,Hyde Park Academy High School
493,Strengthening Resilience in Families and Commu...,2017-04-26 16:00:00,"6220 S Stony Island, Chicago, IL",This workshop will provide tools to support pa...,{'url': 'https://tinyurl.com/CDPHCmtyResil'},Workshop,"Adult | Parents,After-School Providers,Communi...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-26 18:00:00,Hyde Park Academy High School

In [10]:
df['start_time'] = pd.to_datetime(df['start_time'])
df['time'] = pd.DatetimeIndex(df['start_time']).time

In [11]:
df['hour'] = df['start_time'].dt.hour

In [12]:
df.dtypes

event                                  object
start_time                     datetime64[ns]
address                                object
description                            object
web_page                               object
event_type                             object
audience                               object
recurring_event                        object
latitude                              float64
longitude                             float64
location                               object
:@computed_region_rpca_8um6           float64
:@computed_region_vrxf_vc4k           float64
:@computed_region_6mkv_f3dw           float64
:@computed_region_bdys_3d7i           float64
:@computed_region_43wa_7qmu           float64
end_time                       datetime64[ns]
address_details                        object
time                                   object
hour                                    int64
dtype: object

In [13]:
df['hour'].value_counts()

10    159
9     157
11     31
8      31
17     30
18     23
14     23
12     11
13     10
16      8
15      5
7       4
19      1
6       1
Name: hour, dtype: int64

In [14]:
late = df.loc[(df.hour >= 17)]

In [15]:
len(late)

54

In [16]:
late.to_excel(r'C:\Users\Aren Kabarajian\Documents\NYU CUSP\Urban Spatial Final\health_events.xlsx', index = False)

In [17]:
df2 = pd.read_csv('C:/Users/Aren Kabarajian/Documents/NYU CUSP/Urban Spatial Final/Transportation_Network_Providers_-_Trips.csv')

In [18]:
df2.dtypes

Trip ID                        object
Trip Start Timestamp           object
Trip End Timestamp             object
Trip Seconds                    int64
Trip Miles                    float64
Pickup Census Tract           float64
Dropoff Census Tract          float64
Pickup Community Area         float64
Dropoff Community Area        float64
Fare                          float64
Tip                             int64
Additional Charges            float64
Trip Total                    float64
Shared Trip Authorized           bool
Trips Pooled                    int64
Pickup Centroid Latitude      float64
Pickup Centroid Longitude     float64
Pickup Centroid Location       object
Dropoff Centroid Latitude     float64
Dropoff Centroid Longitude    float64
Dropoff Centroid Location      object
dtype: object

In [24]:
df2['Trip Start Timestamp'] = pd.to_datetime(df2['Trip Start Timestamp'])
df2['Trip End Timestamp'] = pd.to_datetime(df2['Trip End Timestamp'])
df2['time'] = pd.DatetimeIndex(df2['Trip Start Timestamp']).time 
df2['hour'] = df2['Trip Start Timestamp'].dt.hour

In [27]:
rideshare_night_trips = df2.loc[(df2.hour >= 18)]

In [28]:
rideshare_night_trips

,Trip ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,Fare,...,Shared Trip Authorized,Trips Pooled,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location,time,hour
71573,f76718ad6c23bc52cfb08543ee022063daaa6a39,2020-09-01 18:00:00,2020-09-01 18:30:00,1896,8.2,NaN,NaN,25.0,NaN,17.5,...,False,1,41.890609,-87.756047,POINT (-87.7560467111 41.8906088526),NaN,NaN,NaN,18:00:00,18
71574,f7214ee9154c4642850c85535120f7a73c5651da,2020-09-01 18:00:00,2020-09-01 18:15:00,408,2.2,NaN,NaN,71.0,68.0,5.0,...,False,1,41.744205,-87.656306,POINT (-87.6563059862 41.7442051463),41.777196,-87.642498,POINT (-87.6424975271 41.7771962546),18:00:00,18
71575,f715876768af513476dc6c06b724584bdc1a6c44,2020-09-01 18:00:00,2020-09-01 18:15:00,965,5.5,NaN,NaN,69.0,49.0,10.0,...,False,1,41.763247,-87.616134,POINT (-87.6161341112 41.7632467988),41.706588,-87.623367,POINT (-87.6233665115 41.7065878819),18:00:00,18
71576,f71048733c081782b2ef24907eca5dfac6073896,2020-09-01 18:00:00,2020-09-01 18:15:00,1262,7.5,1.703108e+10,1.703131e+10,8.0,31.0,17.5,...,False,1,41.907520,-87.626659,POINT (-87.6266589003 41.9075200747),41.855934,-87.668575,POINT (-87.668574537 41.8559343655),18:00:00,18
71577,f704d53274cdf615c421947e17b763b2f74c8768,2020-09-01 18:00:00,2020-09-01 18:00:00,340,1.3,NaN,NaN,41.0,41.0,5.0,...,False,1,41.794090,-87.592311,POINT (-87.592310855 41.794090253),41.794090,-87.592311,POINT (-87.592310855 41.794090253),18:00:00,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
626847,00f07e6456806c12c54da4527b262d235d094c5a,2020-09-05 23:45:00,2020-09-06 00:15:00,1587,17.8,NaN,NaN,33.0,53.0,32.5,...,False,1,41.857184,-87.620335,POINT (-87.6203346241 41.8571838585),41.673820,-87.635740,POINT (-87.6357397768 41.6738199043),23:45:00,23
626848,00cb0038ca0adde2300b3bb4c53fb3859821eee5,2020-09-05 23:45:00,2020-09-06 00:00:00,1030,4.1,1.703124e+10,1.703183e+10,24.0,6.0,12.5,...,False,1,41.899737,-87.664954,POINT (-87.6649539167 41.8997373884),41.945170,-87.668794,POINT (-87.6687944391 41.9451704528),23:45:00,23
626849,0069ef24e967f8438b3604e961ca295b86aada64,2020-09-05 23:45:00,2020-09-06 00:00:00,581,2.1,NaN,NaN,71.0,67.0,5.0,...,False,1,41.744205,-87.656306,POINT (-87.6563059862 41.7442051463),41.775929,-87.666596,POINT (-87.6665962653 41.7759288274),23:45:00,23
626850,0021733bd980f2f9ec2130a7fefcb30bc523b3f4,2020-09-05 23:45:00,2020-09-06 00:00:00,455,3.0,1.703108e+10,1.703124e+10,8.0,24.0,12.5,...,False,1,41.892042,-87.631864,POINT (-87.6318639497 41.8920421365),41.906026,-87.675312,POINT (-87.6753116216 41.906025969),23:45:00,23
626851,000a33e796b659e7e4e9b1cfe897c25bb5a4dcbe,2020-09-05 23:45:00,2020-09-06 00:00:00,779,4.4,1.703101e+10,1.703183e+10,1.0,6.0,10.0,...,False,1,42.000320,-87.663127,POINT (-87.6631267998 42.0003203059),41.945170,-87.668794,POINT (-87.6687944391 41.9451704528),23:45:00,23

In [29]:
rideshare_night_trips.to_excel(r'C:\Users\Aren Kabarajian\Documents\NYU CUSP\Urban Spatial Final\rideshare_night_trips.xlsx', index = False)